class_name AmbienceMap
extends Resource

## EVERYTHING THE VALLEY SOUNDS LIKE, IN ONE `.tres`.
##
## Generated by `tools/generate_ambience.gd` (binding constraint 7), read by
## `src/audio/ambience_director.gd`, and named by nothing else.
##
## ---------------------------------------------------------------------------
## WHAT IS IN HERE AND WHAT IS NOT
## ---------------------------------------------------------------------------
## In here: the bed's layers, the named one-shots, and the three numbers that
## decide how a room differs from a field. Not in here: any name of any weather,
## any threat, or any building. The director resolves those through ids that were
## authored in somebody else's `.tres`.
##
## ---------------------------------------------------------------------------
## THE INTERIOR BLOCK IS AN ACOUSTIC, NOT A VOLUME
## ---------------------------------------------------------------------------
## Stepping inside must not be the wind getting quieter -- that reads as the mix
## being turned down, which is a bug the player attributes to the build. Three
## things move together instead, and each one is a different physical fact:
##
##   `interior_cutoff_hz`  the wall. A low-pass on the bed's own bus, so what is
##                         left of the wind is the part that gets through timber.
##   `interior_radius_m`   the distance. The emitters move OUT, so the wind is
##                         no longer around the listener; it is on the far side
##                         of something.
##   `interior_panning`    the window. Outside, air is everywhere and the bed is
##                         deliberately diffuse; inside, it arrives from one
##                         direction, because it is coming through a gap.
##
## Only the first needs a bus, and the director builds one at runtime rather than
## shipping an `AudioBusLayout` -- `project.godot` is contested by several agents
## at once and a bus layout would be a fourth writer to it.

const SUFFIXES: Array[String] = [".ogg", ".wav", ".mp3"]

## The bed. One voice is built per entry, in order.
@export var layers: Array[AmbienceLayer] = []

## Named one-shots. Optional -- see `AmbienceCue`, a cue with default gain needs
## no row.
@export var cues: Array[AmbienceCue] = []

## ---------------------------------------------------------------------------
## THE FOLDER IS THE DATA
## ---------------------------------------------------------------------------
## Neither the layers nor the cues carry a path in the shipped map, and that is
## deliberate rather than unfinished. A layer named `wind_low` sounds the moment
## `<sound_folder>/wind_low.ogg` is on disk -- no `.gd` edit, no `.tres`
## regeneration, no list to keep in step with a directory.
##
## `CrowCalls` made the same call for the caws and gave the same reason: a list
## that has to be kept in step with a folder is a list that will one day disagree
## with it, and the disagreement is silent.
##
## A row's own `stream_path` still wins when one is authored, which is how a
## layer borrows a file that lives somewhere else.
@export_dir var sound_folder := "res://assets/audio/ambience"

@export_dir var cue_folder := "res://assets/audio/weather"

@export_group("The lead")

## How far into the future the bed samples the wind.
##
## THIS IS THE WHOLE OF "HEARD BEFORE IT IS FELT". `WindSystem`'s model is a pure
## function of t -- its own header says a capture tool can sample the future --
## so the bed asks what the wind will be doing in `lead_seconds` and plays THAT,
## while the tyre swing and the smoke column are still catching up to what it was
## doing a moment ago. The gust is therefore audible before it is visible, in
## every frame, without a single scheduled event.
##
## It is also physically what happens: a squall front two hundred metres out is
## heard long before the air it is pushing arrives.
##
## Kept under a second. Past that the bed stops agreeing with the picture, and a
## sound that predicts too well reads as a mistake rather than as a warning.
@export_range(0.0, 3.0, 0.05) var lead_seconds := 0.85

## Seconds for a voice's gain to close the gap to where the window says it should
## be. SMALL, and it fights the lead: every second of smoothing here is a second
## given back of the lead above. It exists only to stop a per-frame zipper on the
## gain, not to shape anything.
@export var bed_response_seconds := 0.10

@export_group("Placement")

## Where the bed's emitters sit, in metres from the listener, along the direction
## the wind is coming FROM. See `AmbienceDirector.upwind_of()`.
@export var radius_m := 7.0

## `AudioStreamPlayer3D.unit_size` for the bed. Large: the distance is carrying
## direction, not loudness, and a bed that got noticeably louder when the camera
## drifted would read as a bug.
@export var unit_size := 26.0

## 0 is fully diffuse, 1 is fully localised. Outdoors the air is everywhere.
@export_range(0.0, 1.0, 0.01) var panning := 0.35

@export_group("Interior")

## The low-pass cutoff on the bed's bus when the listener is fully inside, and
## when fully outside. 20500 is above hearing and is Godot's own "off" value.
@export var interior_cutoff_hz := 620.0
@export var exterior_cutoff_hz := 20500.0

## Where the emitters move to when inside -- outside the walls.
@export var interior_radius_m := 19.0

## Localised, because inside it arrives through a specific gap.
@export_range(0.0, 1.0, 0.01) var interior_panning := 0.85

## Trimmed as well, but the trim is the SMALLEST of the four changes. If this is
## doing most of the work then the acoustic is not, and the room is just quieter.
@export var interior_gain_db := -5.0

## How long the crossing takes. Roughly a door swinging shut.
@export var interior_response_seconds := 0.55

@export_group("Absence")

## How long the layers marked `withdraws_near_danger` take to leave, and to come
## back.
##
## LEAVING IS SLOWER THAN A CUT AND FASTER THAN A FADE. A cut is a sound effect
## and the player hears the game do something; a slow fade is not noticed at all.
## `MusicMap.silence_fade_seconds` makes the same call for the music.
@export var danger_response_seconds := 1.6

## The hold after a threat is lost, before the top comes back. The same argument
## `MusicMap.post_silence_hold_seconds` makes: the bear wandering off is not the
## same moment as being safe, and snapping the world back on undoes the scene.
@export var danger_hold_seconds := 4.0

@export_group("Fire")

## The loop every member of the `&"fires"` group gets while it is alight. One
## positional voice per fire, so a room with a stove in it sounds like a room
## with a stove in it and the fire is a PLACE rather than a level.
##
## Left empty and resolved as `<sound_folder>/<fire_stem>.<ext>`, the same way
## the layers are.
@export_file("*.wav", "*.ogg", "*.mp3") var fire_stream_path: String = ""

@export var fire_stem: StringName = &"fire"

@export var fire_gain_db := -11.0

## Metres. Past this a fire is not worth a voice.
@export var fire_audible_m := 24.0

@export var fire_unit_size := 6.0

@export_group("Buses")

## Built at runtime by the director if it is not already there -- see the header
## for why this is not an `AudioBusLayout`.
@export var bus: StringName = &"Ambience"

## The fire does NOT go through the bed's low-pass. Being inside muffles the
## wind, which is outside; it does not muffle the stove, which is in the room.
@export var fire_bus: StringName = &"Master"


func layer(layer_id: StringName) -> AmbienceLayer:
	for entry in layers:
		if entry != null and entry.layer_id == layer_id:
			return entry
	return null


func layer_ids() -> Array[StringName]:
	var ids: Array[StringName] = []
	for entry in layers:
		if entry != null and entry.layer_id != &"":
			ids.append(entry.layer_id)
	return ids


func cue(cue_id: StringName) -> AmbienceCue:
	for entry in cues:
		if entry != null and entry.cue_id == cue_id:
			return entry
	return null


## `<folder>/<stem>.<ext>` for the first extension actually on disk, or empty.
##
## Empty is a legal state, not an error: the audio files are owed by the owner
## and every consumer of this is built to be silent until they land rather than
## to complain. Nothing is stubbed with a stand-in, for the reason
## `tools/generate_ui_sounds.gd` gives -- a wrong sound in the right place is
## harder to notice than silence.
static func find(folder: String, stem: String) -> String:
	if folder == "" or stem == "":
		return ""
	for suffix in SUFFIXES:
		var guess := "%s/%s%s" % [folder.trim_suffix("/"), stem, suffix]
		if ResourceLoader.exists(guess):
			return guess
	return ""


## Where a named cue's audio lives: the row's own path if a row declared one,
## otherwise `<cue_folder>/<cue_id>.<ext>`.
func stream_for(cue_id: StringName) -> String:
	if cue_id == &"":
		return ""
	var declared := cue(cue_id)
	if declared != null and declared.stream_path != "":
		return declared.stream_path
	return find(cue_folder, String(cue_id))


## Where a bed layer's audio lives. Same rule, different folder.
func stream_for_layer(entry: AmbienceLayer) -> String:
	if entry == null:
		return ""
	if entry.stream_path != "":
		return entry.stream_path
	return find(sound_folder, String(entry.layer_id))


## The fire loop, by the same convention -- `<sound_folder>/<fire_stem>.<ext>`.
func fire_stream() -> String:
	if fire_stream_path != "":
		return fire_stream_path
	return find(sound_folder, String(fire_stem))


## The cutoff the bus wants at `insideness`, 0 outside .. 1 inside. Pure, so the
## acoustic can be asserted without an AudioServer.
func cutoff_for(insideness: float) -> float:
	return lerpf(exterior_cutoff_hz, interior_cutoff_hz, clampf(insideness, 0.0, 1.0))


func radius_for(insideness: float) -> float:
	return lerpf(radius_m, interior_radius_m, clampf(insideness, 0.0, 1.0))


func panning_for(insideness: float) -> float:
	return lerpf(panning, interior_panning, clampf(insideness, 0.0, 1.0))


func trim_db_for(insideness: float) -> float:
	return lerpf(0.0, interior_gain_db, clampf(insideness, 0.0, 1.0))
