class_name CharacterScheme
extends Resource

## How the wanderer is painted. One `.tres` per look under `data/characters/`.
##
## This exists because there are two defensible answers and the project does not
## have to choose between them.
##
##   * **Pale.** The model's own Meshy maps read at something close to the
##     colours they were painted -- a blue-grey quilted coat, a coral scarf,
##     dark boots. The character's design is visible, which is what the owner
##     asked for, and the figure reads as a person rather than as a shape.
##   * **Dark.** The same maps pulled far down, so the figure is a near-black
##     silhouette with one warm accent. That is how the source video's own
##     frames read, and it buys the one thing pale costs: at gameplay framing
##     the figure is 11% of frame height against a field of bright snow, and a
##     dark shape separates from it at a glance where a mid-tone one does not.
##
## The character is exempt from the Art Bible's surface rules (§2's exception
## box, AssetScanner.SURFACE_RULE_EXEMPT_ROOTS), so unlike everything else in
## the game these colours do not come out of the palette. That is the owner's
## ruling -- 人物的颜色不受 GDD 的影响 -- and it is what makes a scheme possible
## at all.
##
## Adding a third look is a new `.tres` in `data/characters/` and nothing else:
## no `.gd` changes anywhere. Generated by `tools/generate_character_schemes.gd`
## rather than hand-written, per the standing rule about content resources.

@export var id: StringName = &""
@export var display_name: String = ""

## Multiplies the model's own albedo map, and it is the whole of the difference
## between the two shipped looks.
##
## A grey value darkens without shifting hue, which is what a silhouette wants.
## It also *unclips*: at full brightness the scarf's red channel saturates at
## 1.0 while its green and blue are near half, which is what makes a fresh coral
## read as fluorescent orange. Pulling the tint down brings the red back inside
## range and the scarf weathers.
@export var albedo_tint := Color.WHITE

## The maps the material mounts. A scheme that wants a flat shape rather than a
## surface can drop them; both shipped looks keep all three, because the
## quilting on the coat is most of what says "person in a winter coat" at the
## distance this is played at.
@export var normal_map_enabled := true
@export var roughness_map_enabled := true
@export var metallic_map_enabled := true

## The character's own key light, in the scheme rather than beside it because
## the two looks want different amounts of it: modelling is the point of a pale
## figure and irrelevant on a silhouette. 0 means the light is never created.
##
## Aimed from the camera's own quarter -- see PlayerController for why the sun
## cannot do this job.
@export var key_energy := 1.6
@export var key_elevation_degrees := 38.0
@export var key_azimuth_degrees := -25.0
