class_name MusicMap
extends Resource

## The whole music design as data: which tracks play in which situations, how
## long the crossfades are, and -- the load-bearing part -- how much silence
## sits between cues.
##
## Shipped as res://data/audio/music_map.tres, generated by
## tools/generate_music_map.gd (briefing constraint 2.7).
##
## THE SILENCE IS NOT AUTHORED. It used to be: a 150-420 s gap, picked, next to
## a coin flip on whether a situation change brought music in at all. Two
## stacked randomisers, and the result was that a short session could contain
## no music whatever -- which the owner reported, and which cost this system
## the one thing it is for. It is built so that music going away means a threat
## is near; absence cannot say that if absence also happens for no reason.
##
## So there is one number about density here -- gap_cycle_music_share -- and the
## gap is derived from it and from the measured track lengths. See
## gap_mean_seconds. tools/measure_music_density.gd is what settled it, by
## playing hundreds of seven-day runs and counting the seconds.

## Global music level. Every voice is attenuated by this on top of its own
## MusicCue.gain_db. Lower is the safe direction: GDD section 9 makes music a
## survival readout, not a soundtrack, and the loudest thing in this game is
## supposed to be a footstep.
@export var base_volume_db := -8.0

## Length of a track-to-track crossfade. Never a cut.
@export var crossfade_seconds := 6.0

## Length of the fade when music drops away entirely -- the GDD section 9
## "fear by absence" move. Shorter than a crossfade so the disappearance is
## noticeable, long enough that it is not a cut.
@export var silence_fade_seconds := 3.0

## How much of a track-and-gap cycle should have music in it, 0..1. THE knob
## for this whole system, and the only number here that says anything about
## density.
##
## The silence between cues is not authored; it is DERIVED from this and from
## the measured length of the tracks (see gap_mean_seconds). A gap is not a
## constant, it is what a density and a track length imply together, and
## writing it as a constant means a re-cut track silently changes how much
## music the game has and nobody thinks to look here.
##
## IT IS NOT THE SHARE A WHOLE RUN MEASURES, and the gap between the two is
## the difference between a knob and a wish. Every dawn and every nightfall
## brings a track in on top of the cycle (see entry_chance) -- fourteen times
## in a seven-day run -- so a run has a floor near 46% no matter how long the
## gap gets, and the reachable range is only about 46% to 64%. The name says
## `gap_cycle` because that is the part this governs.
##
## Measured with tools/measure_music_density.gd over 200 simulated seven-day
## runs. Move this and re-run that tool. Do not reason about it.
@export_range(0.0, 1.0, 0.01) var gap_cycle_music_share := 0.40

## Full width of the random window the gap is drawn from, centred on the
## derived mean. Not a free number either: it must not exceed
## post_silence_hold_seconds.
##
## The reason is the point of the whole system. A threat's silence is a full
## gap PLUS that hold, so if an ordinary gap can vary by more than the hold,
## an ordinary gap can be as long as a threat's silence and the player cannot
## tell them apart. The randomness in the gap would be larger than the signal
## carried by its length. tools/generate_music_map.gd sets this FROM the hold,
## and test_music_map_data.gd asserts the relationship rather than the number.
@export var gap_window_seconds := 45.0

## The shorter gap used when a situation has just begun and nothing is
## playing, so that dawn gets dawn music rather than having passed by the time
## the long gap expires.
@export var entry_gap_min_seconds := 5.0
@export var entry_gap_max_seconds := 40.0

## Probability that a situation change while silent uses the short entry gap.
##
## THIS IS 1.0 AND SHOULD STAY 1.0. It shipped at 0.5, stacked on top of a
## 150-420 s gap, and the two randomisers together meant a whole session could
## contain no music at all -- the owner reported exactly that. Worse than the
## silence was what it did to the silence that matters: this system is built so
## that music LEAVING says something is near (GDD section 9), and absence
## cannot carry a signal if it also happens for no reason.
##
## Sparseness is the gap's job. It does not need help from a coin flip.
@export var entry_chance := 1.0

## Added to the gap when leaving a silent situation. After a threat has gone,
## the quiet should hang around rather than snapping back to music.
@export var post_silence_hold_seconds := 45.0

## How long after clock.day_started still counts as dawn, and how long after
## clock.night_started still counts as nightfall.
@export var dawn_seconds := 90.0
@export var dusk_seconds := 75.0

## How much the cue drawn last time for a situation is penalised when drawing
## again. 0.0 forbids an immediate repeat outright; 1.0 removes the rule. The
## default leaves a repeat possible but unlikely -- with only two cues cast for
## most situations, an outright ban would make them strictly alternate, which
## is a pattern a player can hear, and the owner asked for random.
@export var repeat_penalty := 0.2

## Audio bus for every music voice. Left on Master because this project has no
## bus layout yet; adding a "Music" bus later is a change to this field, not to
## any script.
@export var bus: StringName = &"Master"

## Situations that are silent by declaration rather than by accident. `danger`
## lives here: GDD section 9 wants the music to drop away when something is
## near, and stating that in data means a later edit cannot quietly turn the
## most important behaviour in the system into a track selection.
@export var silent_situations: Array[StringName] = []

## Situations whose cue plays at once instead of waiting for a gap, and is not
## followed by another. The three endings.
@export var oneshot_situations: Array[StringName] = []

@export var cues: Array[MusicCue] = []

## Used when not one cue carries a measured length, which means the generator
## never ran or ran against missing files. Silence is the safe direction -- a
## derivation that fell through to zero would produce wall-to-wall music, which
## is the loudest possible way to fail -- so an unmeasured map gets three
## minutes of gap rather than none. test_music_map_data.gd makes this
## unreachable for the shipped map.
const UNMEASURED_DURATION_SECONDS := 180.0

## A share of 0 or 1 has no gap that satisfies it, so the derivation is clamped
## rather than allowed to divide by zero. A map that wants no music at all says
## so through silent_situations, which is a statement about a situation rather
## than about arithmetic.
const MIN_SHARE := 0.02
const MAX_SHARE := 0.98

## Weighted mean length of the tracks that can actually be drawn during play.
##
## Weighted by MusicCue.weight, because a track drawn half as often contributes
## half as much to what a player hears. Endings and anything cast only for a
## declared-silent situation are excluded: they never precede a gap.
func mean_cue_duration_seconds() -> float:
	var total := 0.0
	var weight_sum := 0.0
	for cue in cues:
		if cue == null or cue.weight <= 0.0 or cue.duration_seconds <= 0.0:
			continue
		if not _plays_during_the_run(cue):
			continue
		total += cue.duration_seconds * cue.weight
		weight_sum += cue.weight
	if weight_sum <= 0.0:
		return UNMEASURED_DURATION_SECONDS
	return total / weight_sum

## The relationship the gap actually is: a track of length L followed by a gap
## of length G has music sounding L / (L + G) of the time, so hitting a share s
## takes G = L * (1 - s) / s. At a half share the gap is simply the length of a
## track.
func gap_mean_seconds() -> float:
	var share := clampf(gap_cycle_music_share, MIN_SHARE, MAX_SHARE)
	return mean_cue_duration_seconds() * (1.0 - share) / share

func gap_min_seconds() -> float:
	return maxf(0.0, gap_mean_seconds() - maxf(0.0, gap_window_seconds) * 0.5)

func gap_max_seconds() -> float:
	return gap_min_seconds() + maxf(0.0, gap_window_seconds)

func _plays_during_the_run(cue: MusicCue) -> bool:
	for situation in cue.situations:
		if is_silent_situation(situation) or is_oneshot_situation(situation):
			continue
		return true
	return false

func cues_for(situation: StringName) -> Array:
	var out: Array = []
	if situation == &"":
		return out
	for cue in cues:
		if cue != null and cue.plays_in(situation) and cue.weight > 0.0:
			out.append(cue)
	return out

func cue_by_id(id: StringName) -> MusicCue:
	for cue in cues:
		if cue != null and cue.cue_id == id:
			return cue
	return null

func is_silent_situation(situation: StringName) -> bool:
	return silent_situations.has(situation)

func is_oneshot_situation(situation: StringName) -> bool:
	return oneshot_situations.has(situation)
