class_name MusicMap
extends Resource

## The whole music design as data: which tracks play in which situations, how
## long the crossfades are, and -- the load-bearing part -- how much silence
## sits between cues.
##
## Shipped as res://data/audio/music_map.tres, generated by
## tools/generate_music_map.gd (briefing constraint 2.7).

## Global music level. Every voice is attenuated by this on top of its own
## MusicCue.gain_db. Lower is the safe direction: GDD section 9 makes music a
## survival readout, not a soundtrack, and the loudest thing in this game is
## supposed to be a footstep.
@export var base_volume_db := -8.0

## Length of a track-to-track crossfade. Never a cut.
@export var crossfade_seconds := 6.0

## Length of the fade when music drops away entirely -- the GDD section 9
## "fear by absence" move. Shorter than a crossfade so the disappearance is
## noticeable, long enough that it is not a cut.
@export var silence_fade_seconds := 3.0

## Silence between one cue ending and the next beginning. These are the
## numbers that decide whether this reads as a score or as a menu screen, so
## they are deliberately large: with tracks averaging 2.5 minutes, a gap drawn
## from this range leaves music off roughly two thirds of the time.
@export var min_gap_seconds := 150.0
@export var max_gap_seconds := 420.0

## The shorter gap used when a situation has just begun and nothing is
## playing, so that dawn occasionally gets dawn music rather than always
## having passed by the time the long gap expires.
@export var entry_gap_min_seconds := 5.0
@export var entry_gap_max_seconds := 40.0

## Probability that a situation change while silent uses the short entry gap
## at all. Below 1.0 on purpose: at 1.0 every dawn, dusk and nightfall would
## carry music and the run would be scored end to end.
@export var entry_chance := 0.5

## Added to the gap when leaving a silent situation. After a threat has gone,
## the quiet should hang around rather than snapping back to music.
@export var post_silence_hold_seconds := 45.0

## How long after clock.day_started still counts as dawn, and how long after
## clock.night_started still counts as nightfall.
@export var dawn_seconds := 90.0
@export var dusk_seconds := 75.0

## How much the cue drawn last time for a situation is penalised when drawing
## again. 0.0 forbids an immediate repeat outright; 1.0 removes the rule. The
## default leaves a repeat possible but unlikely -- with only two cues cast for
## most situations, an outright ban would make them strictly alternate, which
## is a pattern a player can hear, and the owner asked for random.
@export var repeat_penalty := 0.2

## Audio bus for every music voice. Left on Master because this project has no
## bus layout yet; adding a "Music" bus later is a change to this field, not to
## any script.
@export var bus: StringName = &"Master"

## Situations that are silent by declaration rather than by accident. `danger`
## lives here: GDD section 9 wants the music to drop away when something is
## near, and stating that in data means a later edit cannot quietly turn the
## most important behaviour in the system into a track selection.
@export var silent_situations: Array[StringName] = []

## Situations whose cue plays at once instead of waiting for a gap, and is not
## followed by another. The three endings.
@export var oneshot_situations: Array[StringName] = []

@export var cues: Array[MusicCue] = []

func cues_for(situation: StringName) -> Array:
	var out: Array = []
	if situation == &"":
		return out
	for cue in cues:
		if cue != null and cue.plays_in(situation) and cue.weight > 0.0:
			out.append(cue)
	return out

func cue_by_id(id: StringName) -> MusicCue:
	for cue in cues:
		if cue != null and cue.cue_id == id:
			return cue
	return null

func is_silent_situation(situation: StringName) -> bool:
	return silent_situations.has(situation)

func is_oneshot_situation(situation: StringName) -> bool:
	return oneshot_situations.has(situation)
