class_name OccluderFadeSettings
extends Resource

## How a thing that stands between the camera and the player gets out of the way.
##
## One `.tres` under `data/rendering/`, generated by
## `tools/generate_occluder_fade.gd`. Retuning the effect is an edit to that
## generator and a rerun, not a code change -- the standing rule that content is
## data.

## The colour a faded occluder takes, and how much of it reaches the screen.
##
## ---------------------------------------------------------------------------
## WHY THIS ONE COLOUR IS NOT IN THE 12-COLOUR TABLE
## ---------------------------------------------------------------------------
## The owner's ruling, and it is the same one that already covers the sky, the
## fog and the ambient: **this is a rendering affordance, not an object's
## albedo.** A faded farmhouse is not a farmhouse painted a new colour, it is a
## hole the renderer opens so the player can see his own character.
##
## The palette was tried first, as instructed. Nothing in it reads as 浅灰黑: the
## nine snow tones are all pale blue, the three warm tones are barred by rule 12,
## and the nearest candidate -- `#131C30`, the structure family's darkest, the
## colour the trees are painted -- is unmistakably blue rather than grey, at
## R 19 / G 28 / B 48. Using it would make a faded building read as a translucent
## navy shape, which is "a ghost of its own colour" and is the thing the ruling
## rules out. So the value is off-palette, neutral, and named in the report.
##
## Rule 12 still binds it: warm pixels are reserved for fire, lit windows,
## beacons, the scarf and the truck, and a faded farmhouse covers a good deal
## more of the frame than the half a percent that rule allows.
@export var tint := Color(0.0, 0.0, 0.0, 0.0)

## How long a full fade takes, in seconds, either way.
##
## Short. The effect exists to answer "where is my guy" and an answer that takes
## half a second is a player who has already stopped to look for him. Matched to
## `InteriorReveal.fade_seconds` (0.30) rather than chosen independently, minus a
## little, because these two are the same gesture in the frame and two different
## speeds would read as two different systems.
@export var fade_seconds := 0.22

## How far outside the character's own screen footprint an occluder still counts,
## in pixels. A shape that stops exactly at his outline pops in and out as he
## walks; this starts the fade a little before the overlap.
@export var margin_px := 10.0
