class_name ThresholdCopyMap
extends Resource

## UI design document section 5.2's copy table, as data.
##
## ---------------------------------------------------------------------------
## THIS RESOURCE IS A CONTRACT WITH data/stats/*.tres, AND SECTION 11 ENFORCES IT
## ---------------------------------------------------------------------------
## Section 5.2: 「这张表是本文档与 data/stats/*.tres 的契约。新增一条阈值必须同时在
## 这里加一行文案，否则 UI 会静默地什么也不说.」
##
## tests/unit/test_ui_threshold_copy.gd walks every ThresholdEffect the stat
## files actually author and fails if this map has no row for it. Without that
## gate the first forgotten threshold shows on screen as **nothing at all**, and
## nothing at all is exactly what an untriggered threshold also looks like -- so
## the bug is invisible in play and invisible in review.
##
## ---------------------------------------------------------------------------
## WHY THE TABLE IS DATA AND NOT A CONST DICTIONARY IN THE SURFACING NODE
## ---------------------------------------------------------------------------
## Briefing constraint 4: adding a stat, a threshold or an interlock must be a
## new `.tres` and zero `.gd` changes. A copy table living in GDScript would make
## every new threshold a code change, and the whole data-driven survival model
## would be data-driven right up to the point where it has to say something.
##
## Generated by tools/generate_threshold_copy.gd; never hand-authored
## (constraint 7).

@export var entries: Array[ThresholdCopy] = []

## Thresholds are matched with a tolerance rather than by `==`, because the two
## sides of this contract are two different `.tres` files that were written by
## two different generators and round-tripped through text. The value is half a
## thousandth: a hundredth of the smallest gap between any two authored
## thresholds (0.15 and 0.20 in core_temperature.tres), so it can absorb
## serialisation drift without ever letting one row answer for its neighbour.
const MATCH_TOLERANCE := 0.0005

func row_for(stat: StringName, threshold: float) -> ThresholdCopy:
	for entry in entries:
		if entry == null or entry.stat != stat:
			continue
		if absf(entry.threshold - threshold) <= MATCH_TOLERANCE:
			return entry
	return null

func has_row(stat: StringName, threshold: float) -> bool:
	return row_for(stat, threshold) != null

## Empty string for a threshold with no row, deliberately: the caller decides
## whether to surface a wordless element or nothing at all, and a placeholder
## like "???" would ship to a player.
func text_for(stat: StringName, threshold: float) -> String:
	var row := row_for(stat, threshold)
	return "" if row == null else row.text

## The words for a stat that reached its floor.
##
## Section 3 routes `survival.stat_depleted` to section 5.2 as well, but the copy
## table is keyed by threshold and zero is not one of them -- every authored
## threshold sits strictly above the floor. The lowest row is the right answer
## rather than a fallback: it is the most severe thing the designer wrote about
## that stat, and it is already true at zero. Fatigue's floor gets 跑不动了,
## which is exactly what a fatigue of zero means in GDD section 5's own table.
func lowest_row_for(stat: StringName) -> ThresholdCopy:
	var lowest: ThresholdCopy = null
	for entry in entries:
		if entry == null or entry.stat != stat:
			continue
		if lowest == null or entry.threshold < lowest.threshold:
			lowest = entry
	return lowest

## Every threshold this map has an opinion about, for one stat, worst first.
func thresholds_for(stat: StringName) -> Array[float]:
	var found: Array[float] = []
	for entry in entries:
		if entry != null and entry.stat == stat:
			found.append(entry.threshold)
	found.sort()
	return found

func stat_ids() -> Array[StringName]:
	var found: Array[StringName] = []
	for entry in entries:
		if entry != null and entry.stat != &"" and not found.has(entry.stat):
			found.append(entry.stat)
	return found
