class_name TimePromptData
extends Resource

## UI design document section 5.10: everything the periodic time prompt says and
## how often it says it.
##
## Generated by tools/generate_time_prompt.gd; never hand-authored (briefing
## constraint 7).
##
## ---------------------------------------------------------------------------
## WHY THE TWO WORDS ARE DATA
## ---------------------------------------------------------------------------
## 夜晚, 白天 and the word that labels the day number are the only display copy
## this element has, and section 5.2's fifteen lines are already in data for the
## same reason: copy in a `.gd` file is copy nobody reviews.
##
## ---------------------------------------------------------------------------
## EVERY DEFAULT BELOW IS DELIBERATELY EMPTY
## ---------------------------------------------------------------------------
## ResourceSaver.save() only writes a property that DIFFERS from its script
## default, so a generator that authored the same numbers the definition already
## declared produced a `.tres` holding nothing but its own script path. It loaded
## and behaved correctly, which is the problem: the data file is supposed to be
## the authority, and an empty one is indistinguishable from a generator that
## failed.
##
## So the definition declares the SHAPE and the generator declares the CONTENT,
## and every authored value ends up in the file where it can be read. A prompt
## whose data failed to load is inert rather than quietly running on numbers
## nobody can see (see TimePrompt: no data, no prompt).
##
## ---------------------------------------------------------------------------
## AND WHY THE CADENCE IS
## ---------------------------------------------------------------------------
## `hours_between` is a pacing decision, not an implementation detail. Constraint
## 4's spirit: changing how often the world tells the time should be a `.tres`
## edit. What is NOT here is how long an hour lasts -- see TimePrompt, which
## works that out from the day the schedule authored, because an hour that did
## not follow the run's own pacing would drift out of agreement with it the first
## time a day was retuned.

## 白天 / 夜晚. What the prompt calls each phase of WorldClock.
@export var day_label: String = ""
@export var night_label: String = ""

## The word that labels the day number: `Day 4` rather than a bare `4`.
##
## ---------------------------------------------------------------------------
## WHY THERE IS A WORD HERE AT ALL, AND WHY IT HAS NO DENOMINATOR
## ---------------------------------------------------------------------------
## Shipped bare, the line read `夜晚 1`, and a reader cannot tell whether that 1
## is the day or an index of the night. The label settles it, and it is the
## owner's own ruling: 最好加上 Day 不需要说第几天.
##
## It is deliberately NOT `第 N 日`. That form was ruled out by name.
##
## And there is deliberately no total. `Day 3 / 7` would turn the prompt into a
## countdown, and GDD section 4 builds to the seventh day as something endured
## rather than counted down -- the player learns where he is, not how much is
## left. Nothing here reserves room for a denominator, because a seam left for
## one is an invitation to add it.
@export var day_word: String = ""

## How often it appears, in hours of world time.
@export var hours_between: float = 0.0

## How many hours are in one day-night cycle. The divisor that turns a schedule's
## seconds into hours; 24 because a day is a day.
@export var hours_per_day: float = 0.0

## Section 1.2's 持, in seconds. The 呵 and the 散 come from the tokens, so
## section 5.6's cold snap reaches this element like every other one.
@export var hold_seconds: float = 0.0

## The span of the arc, in degrees. Shallow: the reference shows a sixth of a
## circle, which is an arc you read as a path rather than as a dial.
@export var arc_degrees: float = 0.0

## The chord the arc spans and how far the icons stand from it, in design pixels
## against section 2.3's 1080 reference. Everything else in the element is
## derived from these, so it scales as one object.
@export var arc_width_design_px: float = 0.0
@export var icon_design_px: float = 0.0
@export var gap_design_px: float = 0.0

## Section 2.2's Body, for the phase word, with its CJK tracking.
@export var label_design_px: float = 0.0
@export var label_tracking_em: float = 0.0

## The two faces, named without their extension: `assets/ui/icons/<glyph>.png`.
## White on transparent and tinted at runtime, so a file that arrives carrying
## its own colour is a defect rather than something to compensate for in code.
@export var day_glyph: StringName = &""
@export var night_glyph: StringName = &""
