class_name UITokens
extends Resource

## The design tokens of the UI design document, sections 2.1 through 2.4.
## Generated by tools/generate_ui_tokens.gd; never hand-authored (briefing
## constraint 7).
##
## ---------------------------------------------------------------------------
## WHY THE COLOURS ARE COPIED HERE RATHER THAN LOOKED UP
## ---------------------------------------------------------------------------
## Every colour below is one of the twelve in data/palette/color_bible.tres, and
## the generator reads them OUT of that file rather than writing hex -- so there
## is still exactly one place in the project where a colour is authored, which is
## what constraint 6 is protecting.
##
## Storing the resolved values rather than indices into the palette buys the one
## thing that matters at runtime: a Control can read `tokens.ink_primary` without
## the palette being loaded at all. The cost is that the two files can drift if
## somebody edits the palette and forgets to re-run the generator -- and that is
## closed by tests/unit/test_ui_tokens.gd, which asserts every token IS the
## palette entry the design document names. Drift fails the suite rather than
## quietly shipping an off-palette interface.
##
## ---------------------------------------------------------------------------
## WHY MOTION AND FONTS LIVE IN THE SAME RESOURCE
## ---------------------------------------------------------------------------
## Because the design document treats them as one thing, and because the whole
## point of section 2.4 is that the durations are a SYSTEM: the cold snap
## multiplies all of them at once (section 5.6), and a system you can multiply is
## one that has to be readable from one place.

# --- colour (section 2.1) ---------------------------------------------------

@export var ink_primary: Color = Color.WHITE
@export var ink_secondary: Color = Color.WHITE
@export var ink_muted: Color = Color.WHITE
@export var line_hairline: Color = Color.WHITE
@export var line_deep: Color = Color.WHITE
@export var scrim_veil: Color = Color.BLACK
@export var life_warm: Color = Color.WHITE
@export var life_ember: Color = Color.WHITE
@export var alarm_blood: Color = Color.WHITE

## Section 2.1's ladder, and there are no values between the rungs. Authored as
## a list rather than as five named floats so that "is this opacity legal" is a
## question code can ask.
@export var opacity_steps: PackedFloat32Array = PackedFloat32Array()

# --- geometry (section 2.3) -------------------------------------------------

## Design pixels are authored against 1080 and scaled from there.
@export var reference_height: int = 1080

## Every gap between elements is a multiple of this, in design pixels.
@export var grid_unit: int = 8

## The breathing border, as a fraction of the SHORT edge. See edge_pixels().
@export var edge_fraction: float = 0.075

# --- motion (section 2.4) ---------------------------------------------------

@export var bloom_seconds: float = 0.20
@export var bloom_heavy_seconds: float = 0.32
@export var hold_seconds: float = 2.00
@export var drift_seconds: float = 0.90
@export var drift_fast_seconds: float = 0.40
@export var drift_long_seconds: float = 1.60

## The period warm things pulse at. 4 s is 0.25 Hz, which is the rate section 2.4
## names -- the period is what code integrates, so both are asserted to agree.
@export var breathe_seconds: float = 4.00
@export var breathe_amplitude: float = 0.14

@export var shiver_hertz: float = 12.0
@export var shiver_pixels: float = 1.0
@export var ripple_seconds: float = 0.30

## Section 5.6: during a cold snap every duration above is multiplied by this and
## NOTHING is added to the screen. The air goes still and so does the interface.
@export var cold_snap_scale: float = 1.40

# --- fonts (section 2.2) ----------------------------------------------------
#
# LATIN IS THE PRIMARY FACE AND CJK IS THE FALLBACK, in both display and
# interface. Getting that round the wrong way raises nothing and renders
# perfectly readable text in the wrong typeface -- see UIFonts and
# assets/fonts/README.md for the mechanism.

@export_file("*.ttf", "*.otf") var display_latin_path: String = ""
@export var display_latin_weight: int = 300
@export_file("*.ttf", "*.otf") var display_cjk_path: String = ""

## 200 is not a preference, it is the floor of NotoSerifSC-VF's weight axis.
## There is nothing thinner to ask for.
@export var display_cjk_weight: int = 200

@export_file("*.ttf", "*.otf") var interface_latin_path: String = ""
@export var interface_latin_weight: int = 300
@export_file("*.ttf", "*.otf") var interface_cjk_path: String = ""
@export var interface_cjk_weight: int = 300

## Static, single weight, so it carries no weight field. It only ever sets
## numbers, and it must do so with tabular figures -- see UIFonts.
@export_file("*.ttf", "*.otf") var instrument_path: String = ""

# --- reading ----------------------------------------------------------------

## Token name -> colour, for code that wants to look one up by the name the
## design document uses. The order is section 2.1's order.
func colour_token_names() -> Array[StringName]:
	return [
		&"ink/primary", &"ink/secondary", &"ink/muted",
		&"line/hairline", &"line/deep", &"scrim/veil",
		&"life/warm", &"life/ember", &"alarm/blood",
	]

## Magenta for an unknown name, deliberately: a typo should be visible on screen
## at once rather than resolving to something plausible. Magenta is not in the
## twelve, so tests/art/test_ui_palette.gd catches it too.
func colour(token: StringName) -> Color:
	match token:
		&"ink/primary": return ink_primary
		&"ink/secondary": return ink_secondary
		&"ink/muted": return ink_muted
		&"line/hairline": return line_hairline
		&"line/deep": return line_deep
		&"scrim/veil": return scrim_veil
		&"life/warm": return life_warm
		&"life/ember": return life_ember
		&"alarm/blood": return alarm_blood
	return Color.MAGENTA

func font_paths() -> Array[String]:
	var paths: Array[String] = []
	for path in [display_latin_path, display_cjk_path,
				 interface_latin_path, interface_cjk_path, instrument_path]:
		if path != "":
			paths.append(path)
	return paths

# --- geometry ---------------------------------------------------------------

## Design pixels to screen pixels, driven by the SHORT edge.
##
## The project stretches with `canvas_items` / `expand` (System Map section 8),
## which reveals extra screen area rather than letterboxing it. Scaling off the
## short edge is what makes an ultrawide window show MORE VALLEY at the same UI
## size, instead of a UI that grows with the monitor.
func scale_for(viewport_size: Vector2) -> float:
	var short_edge := minf(viewport_size.x, viewport_size.y)
	if reference_height <= 0:
		return 1.0
	return short_edge / float(reference_height)

func design_px(design_pixels: float, viewport_size: Vector2) -> float:
	return design_pixels * scale_for(viewport_size)

## The breathing border of section 2.3, in screen pixels.
##
## Off the SHORT edge, not off each axis separately. Measuring each margin
## against its own axis would put a 192 px left border and an 81 px top border on
## a 2560x1080 monitor, and rule 2's "the middle is the world" would read as a
## different composition at every aspect ratio.
func edge_pixels(viewport_size: Vector2) -> float:
	return minf(viewport_size.x, viewport_size.y) * edge_fraction

## Spacing on the 8 px grid, in screen pixels. `units` is grid units, not pixels.
func gap(units: float, viewport_size: Vector2) -> float:
	return design_px(units * float(grid_unit), viewport_size)
