class_name VitalLayout
extends Resource

## The order and the shape of the survival readings, for both the permanent
## stack in the breathing margin and section 6.1's ring.
##
## Generated by tools/generate_vital_layout.gd; never hand-authored (briefing
## constraint 7). tests/unit/test_vital_layout.gd holds it to data/stats/*.tres
## the same way the copy table is held to it: a stat with no row here is a stat
## the player cannot see, and that failure looks exactly like a stat that has not
## moved yet.

@export var readouts: Array[VitalReadout] = []

## Section 6.1: 段间空隙 14°.
@export var ring_gap_degrees: float = 14.0

## Section 6.1: 半径 = 1.6 × 角色屏幕高度.
@export var ring_radius_ratio: float = 1.6

## The reading the interface's own ice is made of.
##
## Frost accumulates and clears with how cold the body is, so something has to
## say which reading IS the cold. Named here rather than inferred from
## `lethal_at_min`, because SurvivalSystem publishes values and not definitions
## and the readout has no business loading the stat files a second time to find
## out -- and because "the stat that kills you" and "the stat that makes ice"
## happen to coincide today and are not the same claim.
## The one reading allowed to be warm.
##
## Rule 3 gives warm exactly one meaning -- 热量的存在 -- and the day dial is warm
## because SUNLIGHT IS HEAT. Named in data rather than inferred, so the ruling is
## visible where the layout is, and so nothing in src/ui decides it by a stat's
## name.
@export var warm_source: StringName = &"daylight"


## Rows in the order they are drawn.
func ordered() -> Array[VitalReadout]:
	var rows: Array[VitalReadout] = []
	for row in readouts:
		if row != null and row.stat != &"":
			rows.append(row)
	rows.sort_custom(func(a: VitalReadout, b: VitalReadout) -> bool: return a.order < b.order)
	return rows


## Only the rows that live on the ring. Section 6.1 keeps frostbite off it.
func ring_rows() -> Array[VitalReadout]:
	var rows: Array[VitalReadout] = []
	for row in ordered():
		if row.ring_anchor == VitalReadout.Anchor.RING:
			rows.append(row)
	return rows


func row_for(stat: StringName) -> VitalReadout:
	for row in readouts:
		if row != null and (row.stat == stat or row.second_stat == stat):
			return row
	return null


## Only the readings that come from the survival model. The day dial does not.
func stat_rows() -> Array[VitalReadout]:
	var rows: Array[VitalReadout] = []
	for row in ordered():
		if row.source == VitalReadout.Source.STAT:
			rows.append(row)
	return rows


func has_row(stat: StringName) -> bool:
	return row_for(stat) != null


## What the interface calls a stat. Empty rather than a fallback to the stat id:
## a raw `frostbite_hands` on screen is worse than no label, and it is the sort
## of thing that ships because it looks like a deliberate placeholder.
func label_for(stat: StringName) -> String:
	var row := row_for(stat)
	return "" if row == null else row.label


## What the ring's segments and gaps leave over.
##
## Section 6.1's own numbers do not close a circle: 110 + 58 * 3 = 284 degrees of
## segment, plus four 14 degree gaps, is 340. The remaining 20 degrees are not a
## rounding error -- the diagram shows the ring OPEN at the bottom, which is
## where the hand and foot arcs stand. This is that opening, computed rather than
## authored so it cannot drift out of agreement with the rows.
func ring_opening_degrees() -> float:
	var used := 0.0
	var rows := ring_rows()
	for row in rows:
		used += row.ring_degrees
	used += ring_gap_degrees * float(rows.size())
	return 360.0 - used
