class_name WindProfile
extends Resource

## The CHARACTER of a wind, as data. One `.tres` under `data/weather/`,
## generated by `tools/generate_wind_profiles.gd`.
##
## ---------------------------------------------------------------------------
## WHY THE CHARACTER IS THE DATA AND THE STRENGTH IS NOT
## ---------------------------------------------------------------------------
## Wind is invisible. The player never sees a vector; he sees what it moves. And
## the second half of that, which decides whether any of this reads at all: a
## CONSTANT wind reads as NO wind. A steady sideways force stops being perceived
## within a few seconds, because nothing about it changes. What is perceived as
## wind is the CHANGE -- a gust arriving, a lull, a squall crossing the valley
## and passing.
##
## So the numbers that matter here are the ones that describe the change:
## `gust_seconds`, `gust_depth`, `gust_sharpness`, and the squall block. A weak
## wind with a good gust structure feels far windier than a strong constant one,
## and this file is arranged so a tuner reads that ordering off it.
##
## `base_strength` is deliberately small. It is the floor a lull falls to, not
## the weather.
##
## ---------------------------------------------------------------------------
## ADDING A GALE IS ADDING A FILE
## ---------------------------------------------------------------------------
## Binding rule 4. A later weather event brings its own weather by naming a
## different profile -- `data/weather/wind_gale.tres` ships alongside the valley
## default for exactly that reason, and nothing in `src/` changed to make it
## possible. `WindSystem.set_profile()` is where a weather system connects.

@export var id: StringName = &""
@export var display_name: String = ""

@export_group("Direction")

## Where the wind comes FROM -- no. Where it BLOWS TO, in degrees about +Y, with
## 0 along +X and 90 along +Z. Stated as the direction of travel because every
## consumer in this game takes a travel vector, and a meteorological "from"
## bearing would be the one place in the pipeline where the sign flips.
##
## The default is not a taste: it is `Snowfall.gale_wind`, which was art-directed
## against the camera's fixed -35 degree yaw so that the snow crosses the frame
## from the left rather than into or out of it. atan2(0.5, 1.6) = 17.354 degrees.
## `tests/unit/test_wind.gd` pins the two together so they cannot drift apart.
@export var prevailing_degrees := 17.354

## How far the heading wanders either side of prevailing, and how long a full
## wander takes. Slow: a valley wind swings over a minute, not over a breath.
@export var wander_degrees := 24.0
@export var wander_seconds := 47.0

## How far a gust VEERS the heading at its peak. Small, and it exists because a
## gust that arrives from exactly the same quarter as the lull it interrupts
## reads as a volume knob rather than as weather.
@export var gust_veer_degrees := 13.0

@export_group("Strength")

## The lull floor, 0 dead still .. 1 full gale. The wind never falls below this.
@export var base_strength := 0.06

## How much a full gust adds on top of the floor.
@export var gust_depth := 0.34

## Seconds for the slowest of the three gust octaves. The other two are at
## 1/2.7 and 1/6.3 of it -- incommensurate on purpose, so the pattern never
## audibly repeats.
@export var gust_seconds := 9.0

## The exponent the 0..1 gust field is raised to. Above 1 this makes lulls long
## and gusts brief, which is what wind actually does; at 1 it is a sine and reads
## as a machine.
@export var gust_sharpness := 2.2

@export_group("Squall")

## The big one: a front crossing the valley and passing. Adds on top of the gust
## structure, arrives on a jittered schedule, and is the event the player
## remembers. Set `squall_gain` to 0 to switch it off.
@export var squall_gain := 0.44

## How long one squall lasts, and how much of that is spent arriving and
## leaving, as fractions of the whole. Arriving is quicker than leaving, which is
## the asymmetry that makes it read as a thing that hit rather than a thing that
## was faded in.
@export var squall_seconds := 13.0
@export var squall_attack := 0.22
@export var squall_release := 0.46

## Mean seconds between squalls, and how much that interval varies, 0 .. 1.
@export var squall_interval_seconds := 76.0
@export var squall_interval_jitter := 0.55

@export_group("Vocabulary")

## What a strength of 1.0 means in the metres-per-second-squared that every
## consumer's `set_wind()` actually takes.
##
## ---------------------------------------------------------------------------
## THIS NUMBER IS A RECONCILIATION, NOT A CHOICE
## ---------------------------------------------------------------------------
## Three files already share a wind vocabulary -- `SnowfallLayer.set_wind()`,
## `BreathFog.set_wind()`, `SnowLoad.set_wind()` -- and every one of them adds
## the vector straight into a `ParticleProcessMaterial.gravity`, which is an
## ACCELERATION. The parameter is named `velocity` in all three and the
## producer-side helper is named `wind_velocity()`. The name is wrong everywhere
## and consistently; the unit is m/s^2 everywhere and consistently.
##
## Only one of the three carried a magnitude: `Snowfall.gale_wind`, at
## |(1.6, 0, 0.5)| = 1.6763. That is the authored figure and it is kept exactly,
## so the wind system taking ownership of the vocabulary changes no picture that
## was already tuned.
@export var gale_metres := 1.6763055

@export_group("Reporting")

## The strength a gust has to reach before `wind.gust_started` is published, and
## how far back down it has to come before `wind.gust_ended` is. The gap is
## hysteresis: without it a strength hovering on the threshold publishes a storm
## of events, which is worse for an audio system than no event at all.
@export var gust_threshold := 0.30
@export var gust_hysteresis := 0.09

## The strength the wind has to fall BELOW for `wind.lull_started`. GDD section 7
## makes the still air its own weather -- 寒流's tell is 空气变得极静 -- and
## section 9's scare is the world going quiet. An audio system needs the onset of
## the silence as much as the onset of the noise.
@export var lull_threshold := 0.12
@export var lull_hysteresis := 0.05

## How far the heading has to move, in degrees, before `wind.direction_shifted`
## is published. GDD section 8 hangs the bear's nose on this and section 7 has a
## whole event (风向突变) whose entire content is the heading changing.
@export var direction_report_degrees := 18.0
